### ISSUE TITLE
How the ordinals-api should configure link hooks

### ISSUE THREAD

**Issue by pupudaye** [hirosystems/ordhook#126]
I use the relevant information below to start the chain hook only to see the structure, but not to start port monitoring.
If I want to use ordinals-api, chainhook doesn't have listening port, I can't configure ordinals-api env.ts correctly

chainhook service start --predicate-path=./ordinals.json --config-path=./config.toml

[storage]
driver = "memory"
redis_uri = ""
cache_path = "./data2"

[chainhooks]
max_stacks_registrations = 500
max_bitcoin_registrations = 500

[network]
mode = "mainnet"
bitcoind_rpc_url = ""
bitcoind_rpc_username = ""
bitcoind_rpc_password = ""
stacks_node_rpc_url = "https://stacks-node-api.mainnet.stacks.co/"

{
"chain": "bitcoin",
"uuid": "818725a4-555d-46db-a60c-213a506b37ba",
"name": "inscription_feed",
"version": 1,
"networks": {
"mainnet": {
"start_block": 767430,
"end_block": 793083,
"if_this": {
"scope": "ordinals_protocol",
"operation": "inscription_feed"
},
"then_that": {
"file_append": {
"path": "ordinals.txt"
}
}
}
}
}

**Comment by LakshmiLavanyaKasturi** [comment]
@lgalabru, I guess this is now handled using Ordhook in the documentation here. https://github.com/hirosystems/ordhook#run-ordhook-as-a-service-for-streaming-blocks. Please correct me if I am wrong.

**Comment by lgalabru** [comment]
Closing this issue @pupudaye feel free to re-open if you think the documentation can be improved.
