### ISSUE TITLE
Another issue that might be critical in Ordhook.

### ISSUE THREAD

**Issue by jwest951227** [hirosystems/ordhook#372]
A critical issue with Ordhook is its vulnerability to network reorganizations, which can lead to inconsistencies in indexed data and disrupt applications relying on it. To address this, implementing a robust real-time monitoring system that tracks network changes and dynamically updates indexed data can enhance resilience against re-org events.

**Comment by smcclellan** [comment]
Thank you for filing this. We are tracking the work here on [this ticket](https://github.com/hirosystems/chainhook/issues/695).
